### ISSUE TITLE
Remove objectassign

### ISSUE THREAD

**Issue by chrsdietz** [bespoken/dashboard#178] opened 2017-01-11 19:26 UTC
Since Typescript implemented [Spreading](https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/), there should be no more need to import `objectassign` in any files.   This could safely be removed.

**Comment by michaelmyers** [comment] 2017-01-12 15:58
You must really want to get rid of objectAssign, this is a dupe of your earlier issue #122

**Closed by michaelmyers** 2017-01-12 15:58 UTC
Labels: duplicate, enhancement
